spring:
  application:
    name: teach-back

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 30
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: true

  flyway:
    baseline-on-migrate: true
server:
  port: 8888

scalar:
  enabled: true
  dark-mode: true
  layout: modern
