spring:
  application:
    name: teach-back

  datasource:
    url: jdbc:postgresql://postgres:5432/animal
    username: animal
    password: animal
    hikari:
      maximum-pool-size: 30
    driver-class-name: org.postgresql.Driver


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/teach-realm
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: true

server:
  port: 8888

scalar:
  enabled: true
  dark-mode: true
  layout: modern
